### ISSUE TITLE
How do I run this on Mac

### ISSUE THREAD

**Issue by Emmadgithub** [diStyApps/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI#15]
### Discussed in https://github.com/diStyApps/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/discussions/14

<div type='discussions-op-text'>

<sup>Originally posted by **Emmadgithub** January  7, 2023</sup>
Hello, I'm slightly new to coding and I downloaded this to convert some of the Diffusion model files in safe tensor to CKPT to run them in diffusion BEE, Please do let me know how to run this.
thanks 
<img width="625" alt="Screenshot 2023-01-07 at 6 10 54 PM" src="https://user-images.githubusercontent.com/121051441/211152391-748714f1-1a60-4bb7-942f-4e0fe94fc22a.png">
</div>

**Comment by diStyApps** [comment]
Solved [#14](https://github.com/diStyApps/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/discussions/14)
