### ISSUE TITLE
Error: [Errno 13] Permission denied: 'C:\\Safetensor2-cnvrtd.ckpt'

### ISSUE THREAD

**Issue by benagastov** [diStyApps/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI#16]
I try to convert safetensor back to ckpt for using with some old webui with faster iteration feature. Unfortunately it didnt support safetensor so I have to convert it back to ckpt. But when I use your GUI why  it shows Error: [Errno 13] Permission denied: 'C:\\Safetensor2-cnvrtd.ckpt'?

Thank you

**Comment by diStyApps** [comment]
Try not using the root directory (C:) directly. Instead, try using a subdirectory, like C:\Folder\Safetensor2-cnvrtd.ckpt.

Tell me if it helped you.
