### ISSUE TITLE
Error: Key `state_dict` is invalid, expected torch.Tensor but received <class 'dict'>

### ISSUE THREAD

**Issue by Oricul** [diStyApps/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI#3]
### Current Behavior:
Certain ckpt fail to convert with the following error message:
Error: Key `state_dict` is invalid, expected torch.Tensor but received <class 'dict'>

### Expected Behavior:
Ckpt should be converted to safetensors.

### Steps To Reproduce:
1. Open run_app_gui.exe.
2. Point file dialog at either of the ckpts.
3. Click Convert.
4. Error upon conversion start.

### Environment:
- OS: Windows 11 21H2, Build 22000.1219

### Anything else:
https://www.reddit.com/r/StableDiffusion/comments/z8mnak/comment/iylgpvq/?utm_source=share&utm_medium=web2x&context=3
> NAI can be converted by adding weights.pop("state_dict") to the conversion script in the [GitHub pull request](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4930).
> Edit: I would also recommend the script from [@Tumppi066](https://gist.github.com/Tumppi066/) which lists and converts models from sub-directories as well as working directory. You can get a NAI compatible version I patched [here](https://gist.github.com/RassilonSleeps/edfb630819b95307270efa8450163bc1).

```
import torch
from safetensors.torch import save_file

weights = torch.load("nai.ckpt")["state_dict"]
weights.pop("state_dict")
save_file(weights, "nai.safetensors")
```

**Comment by diStyApps** [comment]
i have added support 
![fix](https://user-images.githubusercontent.com/3084832/205618485-216d656a-cf3d-48eb-93f1-fb6ee0463244.png)

But i haven't tested them yet, working 970 .
If you can test them it will be great.
i think the sd-v1-5-inpainting wont work.
