### ISSUE TITLE
how to run in ubuntu

### ISSUE THREAD

**Issue by lalamax3d** [diStyApps/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI#5]
ubuntu 20, python3.8
pip install -r requirements worked fine. when i run python3 run_app_gui.py it gives

`Traceback (most recent call last):
  File "run_app_gui.py", line 309, in <module>
    main() 
  File "run_app_gui.py", line 66, in main
    file_explorer.layout(),     
  File "/home/user/Data/github/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/util/file_explorer_component.py", line 85, in layout
    sg.Listbox(key=FILE_EXPLORER_LSTBOX_KEY,values=get_system_files_list(),text_color=color.TERMINAL_BLUE,background_color=color.GRAY_1111,
  File "/home/user/Data/github/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/util/file_explorer_component.py", line 79, in get_system_files_list
    return get_system_files(os.path.join(os.getenv("SystemDrive"), "\\"))
  File "/usr/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by diStyApps** [comment]
Thank you for bringing this issue to my attention.

The app currently mainly supports Windows, and thanks to your report, 
And thanks to your report,i installed Ubuntu on WSL and was able to get the app to run. However, it is still not functioning properly and is buggy.
The main problem seems to be with the pathing.
I will try to add full support for Ubuntu and maybe mac at the weekend i hope.

**Comment by lalamax3d** [comment]
Hey, i managed to fix last night and its working fine, i converted few safetensor files to ckpt files :). if you don't mind pull requests, i can open a pull request.

**Comment by diStyApps** [comment]
That is great to hear, and sure open a pull request.
